server:
  port: 8181

spring:
  main:
    banner-mode: off
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  #      settings:
  #        trace: false
  #        web-allow-others: false
  datasource:
    #    url: 'jdbc:h2:file:./h2/spring-boot-h2-db'
    #    username: sa
    #    password: sa
    #    driver-class-name: org.h2.Driver
    url: 'jdbc:postgresql://localhost:5432/lesson'
    username: lesson
    password: lesson
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: 'org.hibernate.dialect.PostgreSQL9Dialect'

tg-bot:
  name: 
  key: 

userbot:
  token: 
  apiid: 
  session-file: example-tdlight-session
  session-data: data
  session-downloads: downloads
